### ISSUE TITLE
On edit page, `add id` btn not working

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1346]
Related to #1328
@seabelis notices the `add id` button on edit page is also not working.

**Comment by seabelis** [comment]
Can probably change this to all buttons not working. Cannot add an additional contributor (editor, etc.) either.

**Comment by LeadSongDog** [comment]
It isn't just buttons. The "Librarian Mode" link on the edit page doesn't work either. 
<a title="Expose another 20 fields about the edition" id="libraryMode" accesskey="l" href="javascript:;">Librarian Mode</a>

**Comment by seabelis** [comment]
Yup. https://github.com/internetarchive/openlibrary/issues/1328

**Comment by LeadSongDog** [comment]
Is any javascript still working?

**Comment by mekarpeles** [comment]
Thank you @LeadSongDog! Nothing to be sorry about, in fact that you for bringing this to our attention! Glad we addressed some of these points in #1351 -- re-opening this issue and tagging as `priority`

**Comment by jdlrobson** [comment]
Just want to check I'm understanding the bug here:

![editbook](https://user-images.githubusercontent.com/148752/47062294-1b638880-d18a-11e8-9505-73ac2ba8db68.gif)


I'm seeing
```
vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2 Uncaught Error: Syntax error, unrecognized expression: [input[type!=button], textarea
````
The issue is that selector  -[input[type!=button]
It should be input[type!=button]

**Comment by LeadSongDog** [comment]
Notice that after clicking “Add” the Author “Jon Robson” is _not_ shown under Author “E. B. White”? It used to work until yesterday.

**Comment by mekarpeles** [comment]
```
ncaught Error: Syntax error, unrecognized expression: [input[type!=button], textarea
    at Function.db.error (vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2)
    at ob (vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2)
    at Function.db [as find] (vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2)
    at e.fn.init.find (vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2)
    at e.fn.init.n.fn.init (vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2)
    at new e.fn.init (vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:8)
    at n (vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2)
    at HTMLButtonElement.<anonymous> (all.js?v=75efaef4b4c1d67b5a8ddee4ec3fa326:71)
    at HTMLDocument.dispatch (vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:3)
    at HTMLDocument.r.handle (vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:3)
db.error @ vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2
ob @ vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2
db @ vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2
find @ vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2
n.fn.init @ vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2
e.fn.init @ vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:8
n @ vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:2
(anonymous) @ all.js?v=75efaef4b4c1d67b5a8ddee4ec3fa326:71
dispatch @ vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:3
r.handle @ vendor-v2.js?v=39bab7138f860c0f16ae9721006f1b96:3
```

**Comment by seabelis** [comment]
Still cannot add Amazon.co.uk or Amazon.ca IDs. Amazon.com works. I have not tried the others.

**Comment by LeadSongDog** [comment]
@mekarpeles This is a zombie issue. On chrome/iOS the add button beside the Classification box has disappeared again.

**Comment by seabelis** [comment]
Does each amazon site even need to be specified? The ID's are typically the same across sites.
