### ISSUE TITLE
Error in processing template (items)

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1875]
Observed on https://openlibrary.org/works/OL1066521W/Caesar_and_Cleopatra

![screenshot_20190209-231231_chrome](https://user-images.githubusercontent.com/148752/52541117-6495a480-2d46-11e9-999b-927b0c88864c.jpg)

Expected: error should not occur

**Comment by tfmorris** [comment]
Stack trace available at: https://openlibrary.org/works/OL1066521W/Caesar_and_Cleopatra?debug=true

I've seen this on multiple pages, so it's not an isolated instance.

The parameter doesn't appear to have an `items` attribute, so perhaps it's being passed in with one too many levels of dereferencing?

**Comment by brad2014** [comment]
@jdlrobson this bug is labeled "blocker" - do you mean it blocks the fixing of something else, or that it is high priority?  If the latter, do you have room on your plate to fix it?

**Comment by LeadSongDog** [comment]
It was @tfmorris who added that label, but you raise a good question. So far as I've seen, these labels are not defined anywhere. Perhaps a glossary in the wiki would be in order?

**Comment by mekarpeles** [comment]
Related: #662

**Comment by mekarpeles** [comment]
Fixed by #2104 (in progress)! No results are being returned either because the subjects are not specific enough or the author resolution was failing (possibly because 3 (first middle last) names

**Comment by guyjeangilles** [comment]
#2161 (and the forthcoming related, smaller PRs) seem to have supplanted #2104.

**Comment by cdrini** [comment]
Duplciate of https://github.com/internetarchive/openlibrary/issues/579

**Comment by guyjeangilles** [comment]
@cdrini I think this is a different issue.

I am still seeing the issue above even if I'm not logged in. While #579 only occurs if you are logged in.

**Comment by cdrini** [comment]
@guyjeangilles Looks like you're right! Huh; the error is the same, but it looks like something else must be causing them in these two cases.

**Comment by SouthGoingZax** [comment]
@mekarpeles mentioned that he thinks this has been resolved, so I'll close it.  We can always re-open it if needed.
