### ISSUE TITLE
Book result box spans "indefinitely"

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#5810]
While looking for books in japanese language, discovered book result boxes spanning beyond the standard page width due to too long book titles.

### Evidence / Screenshot (if possible)
![ol-issue-01](https://user-images.githubusercontent.com/73437497/139498739-dc52f228-6d68-47d0-8d66-c8d2a0f52a56.jpg)
![ol-issue-02](https://user-images.githubusercontent.com/73437497/139498752-201492b8-5f46-42b8-9e51-ee215325effd.jpg)

### Relevant url?
https://openlibrary.org/search?q=language%3Ajpn&page=2&sort=new

### Steps to Reproduce

1. Search for `language:jpn`
2. Sort by `Most Recent`
3. Go to page 2

* Actual: Book result box spans "indefinitely"?
* Expected: Book result box width "fixed"

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** Firefox 93.0
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Setting `min-width: 0` on `div#searchResults, div#searchResults ul` should fix it

**Comment by cdrini** [comment]
@shaneriley would you be interested in taking a look at this one? We can help you with any environment issues you're having :)

**Comment by shaneriley** [comment]
Sure, I can prevent it from happening, though it does look like the real issue here is that HTML entities are double-encoded. If the initial ampersand to denote an HTML entity for each character was left as-is, this would render as far fewer characters, and would not cause this overflow. I am still having the issue locally, so I'll post a message in Slack in an attempt to get that resolved. In the meantime, I can fix it in a browser inspector by adding `max-width: 100%` to `div#searchResults` and `overflow: hidden` to `.searchResultItem .details`, so I could just open a PR for those fixes tonight and have you put it up on test to be certain.

**Comment by lephemere** [comment]
Shouldn't the title be continued on the next line below like shown below?

![image](https://user-images.githubusercontent.com/73437497/139921488-a8cd3f55-fad8-4b3c-a84a-4955bcc777ab.png)

**Comment by jimchamp** [comment]
@lephemere normally, that would happen.  This issue occurs specifically if the title has no spaces.

**Comment by cdrini** [comment]
@shaneriley The underlying data issue is reported here: #5809 ; these were imported like this, I'm afraid!

**Comment by homewardgamer** [comment]
I would like to work on this issue, of it's still unresolved.

**Comment by lephemere** [comment]
Same issue happens on the diff view:

![image](https://user-images.githubusercontent.com/73437497/144719887-6b82f23d-2df3-4fb4-bf3c-7e44bcd7e195.png)

See [here](https://openlibrary.org/books/OL34342826M/%E9%9B%91%E8%A8%98%E5%B8%B3_Notebook%E3%80%82_%E4%BB%95%E4%BA%8B%E3%81%A8%E5%AD%A6%E6%A0%A1%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E3%83%8E%E3%83%BC%E3%83%88%E3%80%82_%E3%82%AF%E3%83%A9%E3%82%B7%E3%83%83%E3%82%AF%E3%83%9A%E3%83%BC%E3%83%91%E3%83%BC%E3%83%90%E3%83%83%E3%82%AF_%E7%9A%86%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E5%AE%8C%E5%85%A8%E3%81%AA%E3%82%B8%E3%83%A3%E3%83%BC%E3%83%8A%E3%83%AB%E3%80%82_%E4%B8%8A%E5%8F%B8%E3%82%84%E5%8A%B4%E5%83%8D%E8%80%85%E3%81%AB%E8%89%AF%E3%81%84?m=diff&b=2) for example.

**Comment by Suhas-13** [comment]
Can I work on this?

**Comment by jimchamp** [comment]
@Suhas-13 yes!  Please implement the solution found here: https://github.com/internetarchive/openlibrary/issues/5810#issuecomment-955090315

**Comment by Suhas-13** [comment]
I'm trying to test it out by importing some japanese titles using this guide: https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data, but I'm getting this error: 

Traceback (most recent call last):
  File "/openlibrary/scripts/./copydocs.py", line 11, in <module>
    from scripts.solr_builder.solr_builder.fn_to_cli import FnToCLI
ModuleNotFoundError: No module named 'scripts'

**Comment by jimchamp** [comment]
> Am I missing something?

No, I'm getting the same error when I follow those instructions.  Not sure if the instructions are incorrect, or if `copydocs.py`is somehow broken...

I'm not sure when I'll get a chance to resolve the `copydocs` error, so it may be best to add a book manually to your dev environment here: localhost:8080/books/add

Just make sure that the new book's title is a very long string with no spaces.

**Comment by Suhas-13** [comment]
> Setting `min-width: 0` on `div#searchResults, div#searchResults ul` should fix it

I implemented this solution and it prevents the box itself from overflowing, but if the title is long enough it still leads to this.

![Capture](https://user-images.githubusercontent.com/43460834/181425661-fa82052d-4d3c-44a4-b10a-c3dfbddbd83e.PNG)

**Comment by Suhas-13** [comment]
I added the overflow: hidden to the details class and that seems to fix it: 

![fixed](https://user-images.githubusercontent.com/43460834/181426971-a0a3b0f0-e33f-4299-945b-ce8b4e119eb4.PNG)

**Comment by jimchamp** [comment]
> Is this solution okay @jimchamp?

Looks like it is --- thanks @Suhas-13!
