### ISSUE TITLE
Reading Log menu doesn't close after adding book to list

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6530]
### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by jimchamp** [comment]
Cannot reproduce. More details appreciated.

**Comment by jimchamp** [comment]
I cannot reproduce this when running `master` branch locally or in Gitpod. I'm assuming that this bug has been corrected on `master`, but the change hasn't been deployed to production.

Marking this as "State: Blocked" until our next deployment.

**Comment by jimchamp** [comment]
This appears to happen only when a book is added to the last remaining list displayed in the dropper.  Once this happens, the dropper closes briefly, then reopens.

**Comment by DebbieSan** [comment]
@mekarpeles 
@jimchamp 

Cannot reproduce this behavior. 

Upon investigating, this seems to no longer be an issue and should be closed.

**Comment by mekarpeles** [comment]
I think this is still an issue
![image](https://user-images.githubusercontent.com/978325/229647808-c5868c66-a715-442c-a8e7-fb281658a543.png)
